name: "✨ Feature Request"
description: "Suggest a new idea for the project."
title: "✨ Feat: Brief description of the feature"
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: "## Description\nDescribe the new functionality and why it is useful."

  - type: input
    id: expected_behavior
    attributes:
      label: "Comportamiento esperado"
      placeholder: "Describe cómo debería funcionar la nueva funcionalidad."

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternativas consideradas"
      placeholder: "Explica si has considerado alguna otra opción."

  - type: textarea
    id: additional_info
    attributes:
      label: "Información adicional"
      description: "Comentarios o enlaces adicionales."
